"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EVENTS = void 0;
exports.EVENTS = {
    USER_REGISTERED: 'user.registered',
    USER_LOGGED_IN: 'user.logged_in',
    USER_LOGGED_OUT: 'user.logged_out',
    PASSWORD_RESET_REQUESTED: 'password.reset.requested',
    PASSWORD_CHANGED: 'password.changed',
    MFA_ENABLED: 'mfa.enabled',
    MFA_DISABLED: 'mfa.disabled',
    TENANT_CREATED: 'tenant.created',
    TENANT_UPDATED: 'tenant.updated',
    TENANT_SUSPENDED: 'tenant.suspended',
    TENANT_ACTIVATED: 'tenant.activated',
    TENANT_DELETED: 'tenant.deleted',
    SUBSCRIPTION_UPDATED: 'subscription.updated',
    SUBSCRIPTION_EXPIRED: 'subscription.expired',
    USER_CREATED: 'user.created',
    USER_UPDATED: 'user.updated',
    USER_DELETED: 'user.deleted',
    USER_INVITED: 'user.invited',
    COURSE_CREATED: 'course.created',
    COURSE_UPDATED: 'course.updated',
    COURSE_PUBLISHED: 'course.published',
    COURSE_ARCHIVED: 'course.archived',
    ENROLLMENT_CREATED: 'enrollment.created',
    ENROLLMENT_COMPLETED: 'enrollment.completed',
    ENROLLMENT_CANCELLED: 'enrollment.cancelled',
    QUIZ_SUBMITTED: 'quiz.submitted',
    QUIZ_PASSED: 'quiz.passed',
    QUIZ_FAILED: 'quiz.failed',
    CERTIFICATE_ISSUED: 'certificate.issued',
    NOTIFICATION_SENT: 'notification.sent',
    EMAIL_SENT: 'email.sent',
    PHISHING_SIMULATION_STARTED: 'phishing.simulation.started',
    PHISHING_CLICKED: 'phishing.clicked',
    PHISHING_REPORTED: 'phishing.reported',
};
//# sourceMappingURL=events.js.map