'use client';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardHeader, CardTitle } from '@/components/ui/card';
import { AreaChartCard, BarChartCard, MetricCard, PieChartCard } from '@/components/visualizations';
import { Calendar, Download, FileBarChart, FileText, Filter, TrendingUp } from 'lucide-react';
import Link from 'next/link';

export default function ReportsPage() {
  // Mock data
  const reports = [
    {
      id: 1,
      title: 'Q4 2024 Security Training Report',
      type: 'Training',
      date: '2024-12-15',
      status: 'completed',
    },
    {
      id: 2,
      title: 'Risk Assessment Summary',
      type: 'Risk',
      date: '2024-12-10',
      status: 'completed',
    },
    {
      id: 3,
      title: 'Compliance Audit Report',
      type: 'Compliance',
      date: '2024-12-05',
      status: 'completed',
    },
  ];

  // Report analytics data
  const reportGenerationTrend = [
    { month: 'Jan', generated: 12, downloaded: 10 },
    { month: 'Feb', generated: 15, downloaded: 13 },
    { month: 'Mar', generated: 18, downloaded: 16 },
    { month: 'Apr', generated: 14, downloaded: 12 },
    { month: 'May', generated: 20, downloaded: 18 },
    { month: 'Jun', generated: 22, downloaded: 20 },
  ];

  const reportTypeDistribution = [
    { name: 'Training', value: 45, color: '#3B8EDE' },
    { name: 'Risk Assessment', value: 30, color: '#8CB841' },
    { name: 'Compliance', value: 20, color: '#F5C242' },
    { name: 'Incident', value: 5, color: '#E86A33' },
  ];

  const departmentReportData = [
    { department: 'IT', reports: 28 },
    { department: 'HR', reports: 15 },
    { department: 'Finance', reports: 12 },
    { department: 'Sales', reports: 18 },
    { department: 'Operations', reports: 22 },
  ];

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
        <div>
          <h1 className="text-3xl font-bold">Reports & Analytics</h1>
          <p className="text-muted-foreground">
            Generate and download compliance and training reports
          </p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline">
            <Filter className="mr-2 h-4 w-4" />
            Filter
          </Button>
          <Link href="/reports/builder">
            <Button>
              <FileText className="mr-2 h-4 w-4" />
              Create Report
            </Button>
          </Link>
        </div>
      </div>

      {/* Analytics Overview */}
      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
        <MetricCard
          title="Total Reports"
          value={95}
          subtitle="Generated this quarter"
          trend={{ value: 12.5, isPositive: true, label: 'vs last quarter' }}
          icon={FileBarChart}
          variant="primary"
          animate
        />
        <MetricCard
          title="Reports This Month"
          value={22}
          subtitle="Generated in December"
          trend={{ value: 8.2, isPositive: true, label: 'vs last month' }}
          icon={FileText}
          variant="success"
          animate
        />
        <MetricCard
          title="Avg. Generation Time"
          value="2.5s"
          subtitle="Performance improvement"
          trend={{ value: 15.3, isPositive: true, label: 'faster' }}
          icon={TrendingUp}
          variant="neutral"
          animate
        />
        <MetricCard
          title="Downloads"
          value={180}
          subtitle="Total downloads this quarter"
          trend={{ value: 10.1, isPositive: true, label: 'vs last quarter' }}
          icon={Download}
          variant="primary"
          animate
        />
      </div>

      {/* Charts Section */}
      <div className="grid gap-6 lg:grid-cols-2">
        {/* Report Generation Trend */}
        <AreaChartCard
          title="Report Activity"
          description="Reports generated and downloaded over time"
          data={reportGenerationTrend}
          xAxisKey="month"
          dataKeys={[
            { key: 'generated', name: 'Generated', color: '#3B8EDE' },
            { key: 'downloaded', name: 'Downloaded', color: '#8CB841' },
          ]}
          height={300}
        />

        {/* Report Type Distribution */}
        <PieChartCard
          title="Report Type Distribution"
          description="Breakdown by report category"
          data={reportTypeDistribution}
          height={300}
        />
      </div>

      {/* Department Report Activity */}
      <div className="grid gap-6">
        <BarChartCard
          title="Department Report Activity"
          description="Number of reports generated by department"
          data={departmentReportData}
          xAxisKey="department"
          dataKeys={[{ key: 'reports', name: 'Reports Generated', color: '#3B8EDE' }]}
          height={300}
        />
      </div>

      <div className="grid gap-4">
        {reports.map((report) => (
          <Card key={report.id} className="hover:shadow-lg transition-shadow cursor-pointer">
            <CardHeader>
              <div className="flex items-start justify-between">
                <div className="flex items-start space-x-4">
                  <div className="rounded-full bg-brand-blue/10 p-3">
                    <FileText className="h-6 w-6 text-brand-blue" />
                  </div>
                  <div>
                    <CardTitle>{report.title}</CardTitle>
                    <div className="flex items-center gap-2 mt-2 text-sm text-muted-foreground">
                      <Calendar className="h-4 w-4" />
                      <span>{new Date(report.date).toLocaleDateString()}</span>
                      <Badge variant="info">{report.type}</Badge>
                    </div>
                  </div>
                </div>
                <Button variant="outline" size="sm">
                  <Download className="mr-2 h-4 w-4" />
                  Download
                </Button>
              </div>
            </CardHeader>
          </Card>
        ))}
      </div>
    </div>
  );
}
