export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  TENANT_ADMIN = 'TENANT_ADMIN',
  MANAGER = 'MANAGER',
  USER = 'USER',
  INSTRUCTOR = 'INSTRUCTOR',
}

export enum TenantStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  TRIAL = 'TRIAL',
  EXPIRED = 'EXPIRED',
}

export enum CourseStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum Difficulty {
  BEGINNER = 'BEGINNER',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED',
  EXPERT = 'EXPERT',
}

export enum EnrollmentStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
}

export enum ReportType {
  EXECUTIVE_DASHBOARD = 'EXECUTIVE_DASHBOARD',
  COMPLIANCE_REPORT = 'COMPLIANCE_REPORT',
  USER_PROGRESS = 'USER_PROGRESS',
  PHISHING_SIMULATION = 'PHISHING_SIMULATION',
  RISK_ASSESSMENT = 'RISK_ASSESSMENT',
  TRAINING_EFFECTIVENESS = 'TRAINING_EFFECTIVENESS',
  DEPARTMENT_PERFORMANCE = 'DEPARTMENT_PERFORMANCE',
  CUSTOM = 'CUSTOM',
}

export enum ReportFormat {
  PDF = 'PDF',
  EXCEL = 'EXCEL',
  CSV = 'CSV',
  JSON = 'JSON',
}

export enum ReportStatus {
  PENDING = 'PENDING',
  GENERATING = 'GENERATING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum ComplianceFramework {
  GDPR = 'GDPR',
  HIPAA = 'HIPAA',
  SOC2 = 'SOC2',
  ISO27001 = 'ISO27001',
  NIST = 'NIST',
  PCI_DSS = 'PCI_DSS',
  CCPA = 'CCPA',
}
